### ISSUE TITLE
No module named 'all_tree_generator'

### ISSUE THREAD

**Issue by y1ny** [AbhilashaRavichander/EQUATE#1]
I want to test Q-REAS on a self-constructed dataset. When I run global_reasoner.py, some errors occurred. 

No module named 'all_tree_generator'

Did I miss any files or codes in your repo?

Thanks!

**Comment by AbhilashaRavichander** [comment]
Hi, sorry for the late response! I somehow missed this. The file has been added to the repo. Sorry again!
